
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { type ContractArtifact, loadContractArtifact, type NoirCompiledContract } from '@aztec/aztec.js/abi';
import AMMContractArtifactJson from '../../../contracts/amm_contract/target/amm_contract-AMM.json' with { type: 'json' };
export const AMMContractArtifact = loadContractArtifact(AMMContractArtifactJson as NoirCompiledContract);
