
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { type ContractArtifact, loadContractArtifact, type NoirCompiledContract } from '@aztec/aztec.js/abi';
import TokenContractArtifactJson from '../../../contracts/token_contract/target/token_contract-Token.json' with { type: 'json' };
export const TokenContractArtifact = loadContractArtifact(TokenContractArtifactJson as NoirCompiledContract);
