[package]
name = "individual_swap"
type = "bin"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v4.2.0", directory = "noir-projects/aztec-nr/aztec" }
protocol_types = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v4.2.0", directory = "noir-projects/noir-protocol-circuits/crates/types" }
