[package]
name = "capital_gains_tax"
type = "bin"
authors = [""]

[dependencies]
bb_proof_verification = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v4.1.0-rc.2", directory = "barretenberg/noir/bb_proof_verification" }
protocol_types = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "v4.1.0-rc.2", directory = "noir-projects/noir-protocol-circuits/crates/types" }
