/**
 * Debug: replay summary circuit proofs using WASM backend in Node.js
 * to reproduce the browser stack overflow.
 *
 * Uses saved proof tree data from test/debug-proof-tree-data.json
 * (generated by running `bun test test/pnl.test.ts` with debugOutputPath).
 */
import { Barretenberg, UltraHonkBackend } from '@aztec/bb.js';
import { Noir } from '@aztec/noir-noir_js';
import type { CompiledCircuit } from '@aztec/noir-types';
import fs from 'fs';

const DEBUG_DATA_PATH = 'test/debug-proof-tree-data.json';

const swapSummaryTreeJson = JSON.parse(
    fs.readFileSync('circuits/swap_summary_tree/target/swap_summary_tree.json', 'utf-8')
) as CompiledCircuit;

async function main() {
    if (!fs.existsSync(DEBUG_DATA_PATH)) {
        console.error(`Missing ${DEBUG_DATA_PATH}. Run the PnL test first to generate it:`);
        console.error('  bun test test/pnl.test.ts');
        process.exit(1);
    }

    const debugData = JSON.parse(fs.readFileSync(DEBUG_DATA_PATH, 'utf-8'));
    console.log(`Loaded debug data: ${debugData.leafProofs.length} leaf proofs, ${debugData.combineCalls.length} combine calls`);

    if (debugData.combineCalls.length === 0) {
        console.error('No combine calls found in debug data. Test may not have completed.');
        process.exit(1);
    }

    // Use the first combine call (level 0, leaf-level) as a test case
    const call = debugData.combineCalls[0];
    console.log(`\nUsing combine call: level=${call.level}, isLeafLevel=${call.isLeafLevel}, hasRight=${call.hasRight}`);

    // ============================================================
    // Test 1: Native backend (should work like bun test does)
    // ============================================================
    console.log('\n========================================');
    console.log('Test 1: Native backend (control)');
    console.log('========================================');

    const bbNative = await Barretenberg.new({ threads: 1 });
    await bbNative.initSRSChonk(2 ** 21);

    const nativeNoir = new Noir(swapSummaryTreeJson);
    await nativeNoir.init();
    const nativeBackend = new UltraHonkBackend(swapSummaryTreeJson.bytecode, bbNative);

    // Option A: Re-execute the circuit from summaryInputs
    console.log('\nExecuting summary circuit (native)...');
    const t0 = Date.now();
    const { witness: nativeWitness } = await nativeNoir.execute(call.summaryInputs);
    console.log(`  Execute: ${Date.now() - t0}ms, witness size: ${nativeWitness.length} bytes`);

    console.log('Generating proof (native)...');
    const t1 = Date.now();
    const nativeProof = await nativeBackend.generateProof(nativeWitness, {
        verifierTarget: 'noir-recursive',
    });
    console.log(`  Proof generated: ${Date.now() - t1}ms, proof size: ${nativeProof.proof.length} bytes`);

    const nativeValid = await nativeBackend.verifyProof(nativeProof, {
        verifierTarget: 'noir-recursive',
    });
    console.log(`  Valid: ${nativeValid}`);

    bbNative.destroy();

    // Option B: Use the saved witness directly
    const savedWitness = Buffer.from(call.witness, 'hex');
    console.log(`\nSaved witness size: ${savedWitness.length} bytes, matches re-executed: ${savedWitness.length === nativeWitness.length}`);

    // ============================================================
    // Test 2: WASM backend (simulates browser)
    // ============================================================
    console.log('\n========================================');
    console.log('Test 2: WASM backend (simulates browser)');
    console.log('========================================');

    // Force WASM mode
    const bbWasm = await Barretenberg.new({ threads: 1 });
    await bbWasm.initSRSChonk(2 ** 21);

    const wasmNoir = new Noir(swapSummaryTreeJson);
    await wasmNoir.init();
    const wasmBackend = new UltraHonkBackend(swapSummaryTreeJson.bytecode, bbWasm);

    // Test execute first
    console.log('\nExecuting summary circuit (WASM)...');
    try {
        const t2 = Date.now();
        const { witness: wasmWitness } = await wasmNoir.execute(call.summaryInputs);
        console.log(`  Execute: ${Date.now() - t2}ms, witness size: ${wasmWitness.length} bytes`);

        // Test proof generation
        console.log('Generating proof (WASM)...');
        const t3 = Date.now();
        const wasmProof = await wasmBackend.generateProof(wasmWitness, {
            verifierTarget: 'noir-recursive',
        });
        console.log(`  Proof generated: ${Date.now() - t3}ms, proof size: ${wasmProof.proof.length} bytes`);

        const wasmValid = await wasmBackend.verifyProof(wasmProof, {
            verifierTarget: 'noir-recursive',
        });
        console.log(`  Valid: ${wasmValid}`);
    } catch (e: any) {
        const msg = e.message || e.toString();
        if (msg.includes('stack') || msg.includes('Stack') || msg.includes('RangeError') || msg.includes('memory')) {
            console.error('\n*** STACK OVERFLOW / MEMORY ERROR REPRODUCED ***');
            console.error('Error:', msg.slice(0, 500));
        } else {
            console.error('\nFailed (not stack overflow):', msg.slice(0, 500));
        }
        console.error('\nFull error:', e);
    }

    bbWasm.destroy();

    // ============================================================
    // Test 3: WASM with saved witness (skip execute, just prove)
    // ============================================================
    console.log('\n========================================');
    console.log('Test 3: WASM prove from saved witness');
    console.log('========================================');

    const bbWasm2 = await Barretenberg.new({ threads: 1 });
    await bbWasm2.initSRSChonk(2 ** 21);
    const wasmBackend2 = new UltraHonkBackend(swapSummaryTreeJson.bytecode, bbWasm2);

    try {
        console.log('Generating proof from saved witness (WASM)...');
        const t4 = Date.now();
        const wasmProof2 = await wasmBackend2.generateProof(new Uint8Array(savedWitness), {
            verifierTarget: 'noir-recursive',
        });
        console.log(`  Proof generated: ${Date.now() - t4}ms, proof size: ${wasmProof2.proof.length} bytes`);
    } catch (e: any) {
        const msg = e.message || e.toString();
        if (msg.includes('stack') || msg.includes('Stack') || msg.includes('RangeError') || msg.includes('memory')) {
            console.error('\n*** STACK OVERFLOW / MEMORY ERROR REPRODUCED ***');
            console.error('Error:', msg.slice(0, 500));
        } else {
            console.error('\nFailed (not stack overflow):', msg.slice(0, 500));
        }
    }

    bbWasm2.destroy();

    console.log('\nDone.');
}

main().catch(e => console.error('Fatal:', e));
